# Site settings
title: Comunidad de Aprendizaje | ASJ
description: "Un lugar donde podrás encontrar herramientas para hacer crecer tu comunidad."
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "www.asjhonduras.com" # the name of your domain
logo_url: img/logo_asj.jpg

# Hero
hero: 
    hero_img: comunidad_vecino.jpg
    hero_title: Comunidad de Aprendizaje
    hero_description: Un lugar donde podrás encontrar herramientas para hacer crecer tu comunidad.

# Contact form
api_token: 123

# Contact info
#contact:
    #phone: 932 50 540
    #emergency: 931 53 234
    #email: contact@yoursite.com
    #address: Von schroeders 273, <br> Viña del mar - Chile

# Opening hours
#monday_friday: 9:00 – 18:00
#saturday: 10:00 – 17:00
#sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    #address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
#feed: yes

# Footer
copyright: © 2018 Comunidad de Aprendizaje - Todos los derechos reservados.

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
#analytics: 
#google_verification:
